[package]
name = "endure"
version = "0.0.0-git"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.13", features = ["derive"] }
ctrlc = "3.2.5"
pcap = "1.0.0"
thiserror = "1.0.40"
