# Base image for building the Debian package. The TARGETPLATFORM is an
# automatic build arg set by BuildKit/Buildx to the platform for which
# it is building.
ARG TARGETPLATFORM
FROM rust:1.82-bookworm AS builder

WORKDIR /app

# Copy the project sources.
COPY endure-lib/ ./endure-lib/
COPY endure-macros/ ./endure-macros/
COPY src/ ./src/
COPY Cargo.toml .
COPY Cargo.lock .
COPY LICENSE .

# Install build and runtime dependencies.
RUN apt-get update && apt-get install -y libpcap-dev

# Build the release binary.
RUN cargo build --release

# Install cargo-nfpm for packaging.
RUN cargo install --locked cargo-nfpm

# Create output directory.
RUN mkdir -p /out

# Package .deb into /out.
RUN cargo nfpm package -f deb -o /out

# Export the package to the host system.
FROM scratch AS export
COPY --from=builder /out/*.deb .